name: Build and lint

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-lint:
    name: Build and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - run: npm run update-all
      - run: npm run build-functions
      - run: npm run build:prod
      - run: npm run lint
      - run: npm run lint-functions
