name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  firebase-deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - run: npm run update-all
      - run: npm run build-functions
      - run: npm run build:prod
      - uses: w9jds/firebase-action@master
        with:
          args: deploy -P prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
